### PR TITLE
[Feature-partial] Added the authentication (Login) page implemented

### LINKED ISSUE #190: [Feature Request] Implement Auth Pages
### 🚀 Feature Request

**Description:**
We are looking to create a new **Auth Page** using **React**. This landing page will serve as the first point of contact for users, showcasing our product and encouraging user engagement.

## 📂 Scope

- [ ] 📱 Android
- [ ] 🖥️ Backend
- [X] 🖼️ Frontend
- [ ] 📝 Documentation

### 🎨 Design & Mockup:
LoginPage

### 📋 Requirements:
1. **Light/Dark Mode**

### 🛠️ Tech Stack:
- React
- TypeScript

### 📝 Additional Context:
- You can offer different designs but keep this `eye image`

### PR DESCRIPTION
**Pull request by Anurag-singh-thakur**
# 💬FIXES (#190)

 have added the auth page using the typescript at a route /auth . you can change the route as per your requirements . 

Summary: Added the  exacr same auth page as per the requirements and also added the functionality of dark and light mode as required. i have implemented at a route /auth . you can change the routes as per your requirement 

 (Fixes #190)]

## 📂 Area of Change

- [] 📱 Android
- [] 🖥️ Backend
- [x] 🖼️ Frontend
- [] 📝 Docs

## 🧬 Type of change

- [ ] 🐛 Bug fix 
- [ ] ♻️ Refactor
- [x] ✨ New feature
- [ ] 📦 Dependency upgrade
- [ ] 📝 Documentation update
- [ ] 🔧 Other 

## ✨ What's New

- []

## 🔒 Why

-

## ✅ Changes

- []

## 🛠️ Checklist before requesting a review

- [x ] 🔍 Style guide has been followed
- [ x] 🧑‍💻 Performed a self-review of my code
- [x ] 🔒 No backdated packages have been added

## 💡 Additional informations

-

### CODE REVIEW

**Review by samiurprapon — CHANGES_REQUESTED** [review]
- Missing App Bar
- Non-Responsive on Mobile Devices

**Comment by samiurprapon** [comment]
Please check the mobile Device UI - 
Login(mobile)

**Comment by Anurag-singh-thakur** [comment]
> * Missing App Bar
> * Non-Responsive on Mobile Devices

can you tell  me what is the app bar ...i am making it responsive

**Comment by samiurprapon** [comment]
Appbar means the navigation menu on top of the page `Home` and `Signup` links will be there.

**Review by samiurprapon — APPROVED** [review]

**Comment by samiurprapon** [comment]
@Anurag-singh-thakur thank you for your contribution

**Pull request merged**
